---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
# - name: ubuntu-12.04
#   driver_config:
#     box: opscode-ubuntu-12.04
#     box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
# - name: ubuntu-10.04
#   driver_config:
#     box: opscode-ubuntu-10.04
#     box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: 
    - "recipe[rundeck]"
    - "recipe[rundeck::tool_users]"
  attributes:
    rundeck:
      tool_users:
        use_data_bag: false
        users:
          - id: admin
            encryption: null
            password: admin
            roles: ["admin", "users"]
          - id: jsmith
            encryption: MD5
            password: a029d0df84eb5549c641e04a9ef389e5
            roles: ["admin"]
          - id: steve
            encryption: OBF
            password: 1xfd1zt11uha1ugg1zsp1xfp
            roles: ["admin"]
          - id: bill
            encryption: CRYPT
            password: stnPHOuwRN8Is
            roles: ["admin"]
#- name: ssh_users
# FIXME ssh_users recipe using "search", but chef-solo doesn't support it.
#  run_list:
#    - "recipe[rundeck::ssh_users]"
#  attributes:
